
name: Zero Workflow

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Cleanup Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        keep_minimum_runs: 0
        retain_days: 0
